# Extractor Fan Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acacia360-app-chart.fullname" . }}-extractor-fan-secret
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.extractorFan.secret.DB_USER }}"
  DB_PASSWORD: "{{ .Values.extractorFan.secret.DB_PASSWORD }}"
  JWT_SECRET: "{{ .Values.extractorFan.secret.JWT_SECRET }}"