# Frontend Ingress
{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "acacia360-app-chart.fullname" . }}-frontend-ingress
  labels:
    {{- include "acacia360-app-chart.labels" . | nindent 4 }}
    app: acacia360-frontend
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Accept"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: {{ .Values.frontend.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.frontend.ingress.path }}
            pathType: {{ .Values.frontend.ingress.pathType }}
            backend:
              service:
                name: {{ include "acacia360-app-chart.fullname" . }}-frontend-service
                port:
                  number: {{ .Values.frontend.service.port }}

          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "acacia360-app-chart.fullname" . }}-gateway-service
                port:
                  number: {{ .Values.gateway.service.port }}

          # PMS App route
          - path: /pms/
            pathType: Prefix
            backend:
              service:
                name: acacia-pms-service
                port:
                  number: 8085
{{- end }}